# client-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: { { .Values.client.replicaCount | default 1 } }
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: { { .Values.global.imagePullPolicy } }
          ports:
            - containerPort: { { .Values.client.service.targetPort } }
          env:
            - name: CLIENT_PORT
              value: "3000"
